"""init

Revision ID: 32a2943b6455
Revises: 
Create Date: 2025-08-17 20:54:08.146005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32a2943b6455'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_blocks')
    op.drop_table('learning_user_module_progress')
    op.drop_table('learning_modules')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_modules',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('learning_modules_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('group_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sp_award', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('completion_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='learning_modules_pkey'),
    sa.UniqueConstraint('course_id', 'order', name='uq_course_module_order'),
    sa.UniqueConstraint('course_id', 'title', name='uq_course_module_title'),
    postgresql_ignore_search_path=False
    )
    op.create_table('learning_user_module_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['learning_modules.id'], name='learning_user_module_progress_module_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='learning_user_module_progress_pkey'),
    sa.UniqueConstraint('user_id', 'module_id', name='uq_user_module')
    )
    op.create_table('learning_blocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('video_preview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['learning_modules.id'], name='learning_blocks_module_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='learning_blocks_pkey'),
    sa.UniqueConstraint('module_id', 'order', name='uq_block_order_in_module')
    )
    # ### end Alembic commands ###
