"""make full_description optional

Revision ID: fb69e6de196a
Revises: 662c14ffb98a
Create Date: 2025-07-05 01:44:44.057870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb69e6de196a'
down_revision: Union[str, Sequence[str], None] = '662c14ffb98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homepage_promo_images')
    op.drop_table('courses_courseaccess')
    op.drop_table('homepage_banners')
    op.alter_column('courses_course', 'full_description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses_course', 'full_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table('homepage_banners',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('homepage_banners_pkey'))
    )
    op.create_table('courses_courseaccess',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchased_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses_course.id'], name=op.f('courses_courseaccess_course_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('courses_courseaccess_pkey'))
    )
    op.create_table('homepage_promo_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses_course.id'], name=op.f('homepage_promo_images_course_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('homepage_promo_images_pkey'))
    )
    # ### end Alembic commands ###
